In [1]:
import numpy as np

In [7]:
M = np.array([[1.,2.,3.,4.],[2.,1.,2.,3.],[3.,2.,1.,2.],[4.,3.,2.,1.]])
print(M,"The Matrix")
TheDetermine = np.linalg.det(M)
TheInverse = np.linalg.inv(M)
print(TheDetermine,"The DET[M]")
print(TheReverse,"The inverse[M]")

[[1. 2. 3. 4.]
 [2. 1. 2. 3.]
 [3. 2. 1. 2.]
 [4. 3. 2. 1.]] The Matrix
-19.999999999999996 The DET[M]
[[-4.0000000e-01  5.0000000e-01  0.0000000e+00  1.0000000e-01]
 [ 5.0000000e-01 -1.0000000e+00  5.0000000e-01  0.0000000e+00]
 [ 0.0000000e+00  5.0000000e-01 -1.0000000e+00  5.0000000e-01]
 [ 1.0000000e-01 -6.9388939e-18  5.0000000e-01 -4.0000000e-01]] The inverse[M]


In [10]:
N = np.array([[2,1,0,3],[1,2,1,0],[0,1,2,1],[3,0,1,2]])
print(N,"The Matrix")
n = np.linalg.eig(N)
print(n)

[[2 1 0 3]
 [1 2 1 0]
 [0 1 2 1]
 [3 0 1 2]] The Matrix
EigResult(eigenvalues=array([-1.41421356,  5.41421356,  1.41421356,  2.58578644]), eigenvectors=array([[-0.65328148,  0.65328148,  0.27059805,  0.27059805],
       [ 0.27059805,  0.27059805,  0.65328148, -0.65328148],
       [-0.27059805,  0.27059805, -0.65328148, -0.65328148],
       [ 0.65328148,  0.65328148, -0.27059805,  0.27059805]]))


In [22]:
first = np.array([[5,2,1,1],[2,5,2,1],[1,2,5,2],[2,1,2,5]])
second = np.array([[1],[2],[3],[4]])
print(np.linalg.solve(first,second))
print("The results are respectively correspond to x,y,z and w.")

[[-0.0625    ]
 [ 0.18181818]
 [ 0.26704545]
 [ 0.68181818]]
The results are respectively correspond to x,y,z and w.


In [14]:
f = np.poly1d([1,-2,3,3,-2,1])
print(f.roots,'The roots.')
df = f.deriv()
print(df.roots,"The extremas(don't consider the complex numbers.)")
ddf = df.deriv()
print(ddf.roots)
print(ddf(df.roots),"The second derivatives at critical points(don't consider the complex numbers.)")
print("因為是五次多項式，所以整個函數的極大值或極小值不存在。")
print("所以只有局部極大值或極小值。")
print("由系統執行出來的值可以判斷出：")
print("Local maximum located at x = -0.59909753")
print("Local minimum located at x = 0.25460303")

[ 1.2232207+1.70974018j  1.2232207-1.70974018j -1.       +0.j
  0.2767793+0.38686453j  0.2767793-0.38686453j] The roots.
[ 0.97224725+1.29504247j  0.97224725-1.29504247j -0.59909753+0.j
  0.25460303+0.j        ] The extremas(don't consider the complex numbers.)
[ 0.72031999+0.85312056j  0.72031999-0.85312056j -0.24063999+0.j        ]
[-38.38943541-7.11585041j -38.38943541+7.11585041j
 -17.69832001+0.j           9.35719084+0.j        ] The second derivatives at critical points(don't consider the complex numbers.)
因為是五次多項式，所以整個函數的極大值或極小值不存在。
所以只有局部極大值或極小值。
由系統執行出來的值可以判斷出：
Local maximum located at x = -0.59909753
Local minimum located at x = 0.25460303
