In [4]:
import numpy as np

In [2]:
testing = np.array([[1,2],[5,4],[88,47]])#定義一個陣列
print(testing.ndim)#告訴我是幾維
print(testing.shape)#告訴我是M*N的陣列
print(len(testing))#告訴我M(第一維)
#第一重點

2
(3, 2)
3


In [77]:
b = np.arange(5)#arange是一種屬於numpy的命令，範圍是0~n-1，資料型態是numpy.ndarray
bb = np.arange(4,14,3)#(起始值,終點值(減1才是最後一個理論上會出現的值),公差)
print(b)
print(bb)
print('The data type of arange is: ',type(b))
#可以用type(你要確認的資料)來檢查是甚麼類型
#第二重點

[0 1 2 3 4]
[ 4  7 10 13]
The data type of arange is:  <class 'numpy.ndarray'>


In [4]:
c = np.linspace(0,1,5)#(起始,終點，拆成幾分(預設包含終點,可以改成不包含，見下面))
cc = np.linspace(0,1,5,endpoint=False)
print(c," 拆成五份，有包含終點")
print(cc," 拆成五份，沒有包含終點")

[0.   0.25 0.5  0.75 1.  ]  拆成五份，有包含終點
[0.  0.2 0.4 0.6 0.8]  拆成五份，沒有包含終點


In [5]:
d = np.ones((4,3,2))#建議用兩個括號連接起來，因為只有一個數字一個或兩個括號都可以，但兩個數字以上就一定要兩個括號了。
#順序 = (高,列,行)
#生成全部1或0的陣列
print(d)
dd = np.zeros((5,5))
print(dd)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
e = np.eye(7)#單位矩陣but N*N
print(e)
ee = np.diag([12,2,3,4])#diag = diagonal matrix = 對角矩陣，相當於有些位置不一定是1的單位矩陣。
#其實diag()裡面要放一個矩陣，所以裡面也可以放 np.array([n,n,...])
print(ee)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[12  0  0  0]
 [ 0  2  0  0]
 [ 0  0  3  0]
 [ 0  0  0  4]]


In [29]:
f = np.random.rand(6)#均勻分布，範圍[0,1]，一般用到的"隨機"是這個
ff = np.random.randn(6)#常態分佈，變異數為1，可正可負，the 'n' at fifth place means "normal".，通常用在類神經網路的研究上，較不常用(相對於我)
print(f)
print(ff)

[0.54573365 0.42171837 0.87310659 0.24983121 0.77988423 0.6908006 ]
[-0.26101153  0.25532552  0.83100904 -0.0481497  -0.09864005 -0.53445008]


In [34]:
g = np.array([1,2,4])
gg = np.array([[1,2],[3,4]])
ggg = np.array([1.1,2.2])
gggg = np.array([1,2,3],dtype = float)#第二個參數可以強制改變內部元素資料類型
g1 = np.array([1+4j,2+6j])
gtext = np.array(['hi','okkk'])
gbool = np.array([True,False,False,True,True])
print(g.dtype)
print(gg.dtype)
print(ggg.dtype)
print(gggg.dtype)
print(g1.dtype)
print(gtext.dtype)#會輸出字元數最多的元素的字元數
print(gbool.dtype)
#重點：檢測用.dtype
print(type(g))
print(type(gg))
print(type(ggg))
print(type(gggg))
#結論：用.dtype，檢查的是內部元素的資料類型；用type()，檢查的是整個的資料類型

int32
int32
float64
float64
complex128
<U4
bool
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [79]:
h = np.arange(10)
h[5:] = 37#把序號5以後的元素改為37
print(h)
hh = np.arange(15)
print(hh[-1])#列出最後一項
print(hh[:-1])#列出最後一項之前的元素
print(hh[::3])#從第一個元素開始列出(首項是0)，後面的數字(3)是公差，等差數列出現的數字就是列出的內容的index值。
print(hh[::-3])#同上，不過從最後一個開始
#簡單來說"-"代表的概念是"方向"

[ 0  1  2  3  4 37 37 37 37 37]
14
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  3  6  9 12]
[14 11  8  5  2]


In [98]:
i = np.arange(7)
print(i,'這是一般的數列')

vertical = i[:,np.newaxis]#使其垂直
horizon = i[np.newaxis,:]#使其躺平
#詭異的背法，看第一個參數，冒號是垂直的，"np.newaxis"是橫的
print(vertical,'使其垂直')
print(horizon,'使其躺平')

#可以參考：https://stackoverflow.com/questions/29241056/how-do-i-use-np-newaxis
print("這是講義上的：")
ii = i+np.arange(0,51,10)[:,np.newaxis]
print(ii,'也只能垂直了')

[0 1 2 3 4 5 6] 這是一般的數列
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]] 使其垂直
[[0 1 2 3 4 5 6]] 使其躺平
這是講義上的：
[[ 0  1  2  3  4  5  6]
 [10 11 12 13 14 15 16]
 [20 21 22 23 24 25 26]
 [30 31 32 33 34 35 36]
 [40 41 42 43 44 45 46]
 [50 51 52 53 54 55 56]] 也只能垂直了


In [14]:
#和內部元素的互動
a = np.array([1,2,3,4,5])
print(a)
print(2*a)#內部元素乘以2
b = np.ones((4,4))
print(b)
print(b+7)#內部元素加7
aa = np.array([4,5,6])
bb = np.array([5,6,2])
print(aa*bb)#乘法必須要是同樣size的
j = np.arange(5)
print(j)
print(4*(j+3))

[1 2 3 4 5]
[ 2  4  6  8 10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
[20 30 12]
[0 1 2 3 4]
[12 16 20 24 28]


In [25]:
#矩陣乘法
c = np.array([[1,2],[3,4]])
d = np.array([[3,6],[1,7]])
print(c)
print(d)
print(c*d)#元素相乘，注意size要都一樣才行
print(c.dot(d))#使用dot才是真正的矩陣相乘
print(c == d)
print(c >= d)#邏輯運算，依然注意size

[[1 2]
 [3 4]]
[[3 6]
 [1 7]]
[[ 3 12]
 [ 3 28]]
[[ 5 20]
 [13 46]]
[[False False]
 [False False]]
[[False False]
 [ True False]]


In [59]:
#邏輯運算
a = np.array([1,1,0,0,1,0,1],dtype=bool)#0為False,其餘為1，讓我不用一直輸入True或False。
b = np.array([0,0,1,0,1,1,1],dtype=bool)
print(a)
print(np.logical_or(a,b))#or邏輯運算
print(np.logical_and(a,b))#and邏輯運算
e = np.arange(5)/2* 3.14
print(np.sin(e))#直接把一個範圍的元素當作x並帶入sin(x)裡面計算
print(np.cos(e))

[ True  True False False  True False  True]
[ True  True  True False  True  True  True]
[False False False False  True False  True]
[ 0.          0.99999968  0.00159265 -0.99999715 -0.0031853 ]
[ 1.00000000e+00  7.96326711e-04 -9.99998732e-01 -2.38897811e-03
  9.99994927e-01]


In [68]:
try:
    a = np.arange([7])
    print(a + np.array([1,2]))#array和arange不能相加
except:
    print("array和arange不能相加")

array和arange不能相加


In [81]:
#我先定義左上到右下的線是t
a = np.triu(np.ones((3,3)),0)#數組的上三角形，第二個參數的意思是t往上空幾行開始輸出，0就是從t開始輸出
print(a)
print(a.T)#沿著t做鏡射對換

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [92]:
r = np.array([2,5,8,9])
print(np.sum(r))#使用np功能，引入甚麼參數
print(r.sum())#甚麼物件.做甚麼功能
#上面兩個sum意思一樣
x = np.array([[4,5],[6,2]])
print(x)
print(x.sum(axis = 0))#相加的元素在同一行(column)
print(x.sum(axis = 1))#相加的元素在同一列(row)
#都是先從計算列開始的(上到下)，再從行開始算(左到右)
#對python來說，axis0對應到的是由上到下，axis1對應的則是由左到右

24
24
[[4 5]
 [6 2]]
[10  7]
[9 8]


In [122]:
y = np.array([2,7,9])
print(y.min())
print(y.max())
print(y.argmin())#找index的最小值，看到arg開頭就想到它和index有關
print(y.argmax())#找index的最大值

print(np.all([False,False,True,True,True,False]))#只要有看到一個False就整個都會輸出為False
print(np.any([False,False,True,True,True,False]))#只要有看到一個True就整個會輸出為True

2
9
0
2
False
True


In [165]:
t = np.array([1,2,4,3,5])
u = np.array([[1,7,3],[7,9,6]])
print(u)
print(t.mean())#取平均值
print(np.median(t))#找中間值
print(np.median(u,axis=1))
print(t.std())#找標準差(sigma)

[[1 7 3]
 [7 9 6]]
3.0
3.0
[3. 7.]
1.4142135623730951


In [166]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.ravel()#拆解

array([1, 2, 3, 4, 5, 6])

In [176]:
#np排序工具
a = np.array([[4, 3, 5], [1, 7, 6]])
b = np.sort(a, axis=0)
c = np.sort(a, axis=1)
print(a)
print(b)
print(c)

[[4 3 5]
 [1 7 6]]
[[1 3 5]
 [4 7 6]]
[[3 4 5]
 [1 6 7]]


In [191]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.linalg.inv(a)#inverse反矩陣
c = np.trace(a) # trace
d = np.linalg.det(a)#determine行列式值
#linalg意思應該是linear algebra
y = np.array([[5.], [7.]])
e = np.linalg.solve(a, y)#找出a乘以甚麼會是y

print(a,"the array")
print(b,"the array's inverse version")
print(c,"從最左上角累加到最右下角的值")
print(d,"the determine of the array")
print(e,"找出a乘以甚麼會是y")

[[1. 2.]
 [3. 4.]] the array
[[-2.   1. ]
 [ 1.5 -0.5]] the array's inverse version
5.0 從最左上角累加到最右下角的值
-2.0000000000000004 the determine of the array
[[-3.]
 [ 4.]] 找出a乘以甚麼會是y


In [197]:
M = np.array([[1.0, 2.0], [2.0, 1.0]])
eig_val,Mat_S=np.linalg.eig(M)
print(eig_val)
print(Mat_S)
print(Mat_S.dot(M).dot(np.linalg.inv(Mat_S)))

#線性代數內容，過，看看下面的範例就好

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[-1.00000000e+00  6.66133815e-16]
 [ 6.66133815e-16  3.00000000e+00]]


In [198]:
a = np.array([[1, 2], [3, 4]])
b = np.linalg.eig(a)#找特徵向量
print(a)
print(b)

[[1 2]
 [3 4]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [8]:
p = np.poly1d([3,0,0,0])#相當於3x^3
print(p(0))#x帶0
print(p.roots)#求根
print(p.order)#告訴我這是幾次多項式
print(p)#列出原本的多項式
print(p.deriv())#多項式的微分

0
[0. 0. 0.]
3
   3
3 x
   2
9 x


In [205]:
#numpy筆記到上面結束